# Generated by Django 3.2 on 2021-04-25 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulation_id', models.IntegerField()),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ca1', models.IntegerField(null=True)),
                ('ca2', models.IntegerField(null=True)),
                ('ce1', models.IntegerField(null=True)),
                ('ce2', models.IntegerField(null=True)),
                ('predicted_lift', models.IntegerField(null=True)),
                ('predicted_drag', models.IntegerField(null=True)),
                ('actual_lift', models.IntegerField(null=True)),
                ('actual_drag', models.IntegerField(null=True)),
                ('aoa', models.IntegerField(null=True)),
                ('rn', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
