# Generated by Django 3.2 on 2021-04-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultsmodel',
            name='actual_drag',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='actual_lift',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='ca1',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='ca2',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='ce1',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='ce2',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='predicted_drag',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resultsmodel',
            name='predicted_lift',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
