# Generated by Django 3.2 on 2021-04-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openfoam', '0002_auto_20210426_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultsmodel',
            name='rn',
        ),
        migrations.AddField(
            model_name='simulationmodel',
            name='rn',
            field=models.IntegerField(null=True),
        ),
    ]
